name: PHP CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPStan
        run: composer phpstan

  phpcsfixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHP CS Fixer
        run: composer cs-fix

  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPUnit
        run: composer phpunit

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2.0
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarCloud analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
