name: CI Pipeline

on:
  pull_request:
    branches:
      - main # You can adjust this to your default branch, e.g., 'master'

jobs:
  php-checks:
    runs-on: ubuntu-latest # Using the latest Ubuntu image for the runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP 7.4
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist

      # Step 4: Run PHPStan (static analysis)
      - name: Run PHPStan
        run: composer phpstan

      # Step 5: Run PHP-CS-Fixer
      - name: Run PHP-CS-Fixer
        run: composer cs-fix

      # Step 6: Run SonarQube analysis
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Make sure to add SONAR_TOKEN as a secret in your GitHub repo settings
        run: sonar-scanner
